#!/usr/bin/env python
import os
import shutil
import argparse


def exists(file_name):
    return os.path.exists(file_name) and os.path.isfile(file_name)


parser = argparse.ArgumentParser()
parser.add_argument('SETUP_FOLDER', help='Absolute path to folder to setup cf-setuper')

args = parser.parse_args()
fld = os.path.realpath(args.SETUP_FOLDER)
os.mkdir(fld + '/cf-setuper')
fld += '/cf-setuper'
for file in os.listdir('.'):
    if file.startswith('.') or file == 'install.py':
        continue
    print(file, fld)
    if not os.path.isdir(file):
        shutil.copy2(file, fld)
    else:
        shutil.copytree(file, fld + '/' + file)

os.symlink(fld + '/cf-setuper', '/usr/bin/cf-setuper')
os.system('chmod -R 777 ' + fld)
os.chmod(fld + '/cf-setuper', 0o777)
os.chmod(fld + '/templates/run_tests', 0o777)